# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detcus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, verbose_name='Keterangan Tambahan')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Waktu diedit')),
                ('status', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_delete', models.BooleanField(default=False, verbose_name='Soft Delete')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('photo', models.ImageField(height_field=300, upload_to='uploads/customer', width_field=400)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
