# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160603_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detcus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
